import bedImg from '../../img/cama.jpg'

export const productsData = [
    {
        name: 'a',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        id: 1,
        paymentMethod: ['a vista', 'a prazo'],
        colorMaterial: 'red',
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'b',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'green',
        id: 2,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'c',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'blue',
        id: 3,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'd',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'gray',
        id: 4,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'e',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'orange',
        id: 5,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'f',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'purple',
        id: 6,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'g',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'pink',
        id: 7,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'h',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: 'withe',
        id: 8,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'i',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: '#156487',
        id: 9,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'j',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: '#465873',
        id: 10,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'k',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: '#123456',
        id: 11,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
    {
        name: 'l',
        description: 'uma cama em mdf cinza',
        img: { bedImg },
        price: 800.00,
        colorMaterial: '#987654',
        id: 12,
        paymentMethod: ['a vista', 'a prazo'],
        termPrice: 15,
        quantity: 1,
    },
]